
// Auto-generated by scripts/buildChainMap.ts
// Source: ethereum-lists/chains repository + BIP-44 constants
// Major chains curated based on market cap, TVL, and ecosystem importance

import { ChainInfo } from './types.js';

export const chains: Array<ChainInfo> = [
  {
    "chainId": 1,
    "shortName": "eth",
    "name": "Ethereum Mainnet",
    "coinType": 60,
    "namespace": "eip155",
    "reference": "1"
  },
  {
    "chainId": 137,
    "shortName": "pol",
    "name": "Polygon Mainnet",
    "coinType": 966,
    "namespace": "eip155",
    "reference": "137"
  },
  {
    "chainId": 56,
    "shortName": "bnb",
    "name": "BNB Smart Chain Mainnet",
    "coinType": 714,
    "namespace": "eip155",
    "reference": "56"
  },
  {
    "chainId": 43114,
    "shortName": "avax",
    "name": "Avalanche C-Chain",
    "coinType": 9005,
    "namespace": "eip155",
    "reference": "43114"
  },
  {
    "chainId": 10,
    "shortName": "oeth",
    "name": "OP Mainnet",
    "coinType": 2147483658,
    "namespace": "eip155",
    "reference": "10"
  },
  {
    "chainId": 8453,
    "shortName": "base",
    "name": "Base",
    "coinType": 2147492101,
    "namespace": "eip155",
    "reference": "8453"
  },
  {
    "chainId": 42161,
    "shortName": "arb1",
    "name": "Arbitrum One",
    "coinType": 2147525809,
    "namespace": "eip155",
    "reference": "42161"
  },
  {
    "chainId": 1101,
    "shortName": "zkevm",
    "name": "Polygon zkEVM",
    "coinType": 2147484749,
    "namespace": "eip155",
    "reference": "1101"
  },
  {
    "chainId": 59144,
    "shortName": "linea",
    "name": "Linea",
    "coinType": 2147542792,
    "namespace": "eip155",
    "reference": "59144"
  },
  {
    "chainId": 7777777,
    "shortName": "zora",
    "name": "Zora",
    "coinType": 2155261425,
    "namespace": "eip155",
    "reference": "7777777"
  },
  {
    "chainId": 534352,
    "shortName": "scr",
    "name": "Scroll",
    "coinType": 2148018000,
    "namespace": "eip155",
    "reference": "534352"
  },
  {
    "chainId": 42220,
    "shortName": "celo",
    "name": "Celo Mainnet",
    "coinType": 2147525868,
    "namespace": "eip155",
    "reference": "42220"
  },
  {
    "chainId": "solana",
    "shortName": "solana",
    "name": "Solana",
    "coinType": 501,
    "namespace": "solana",
    "reference": "So11111111111111111111111111111111111111112"
  },
  {
    "chainId": "bitcoin",
    "shortName": "bitcoin",
    "name": "Bitcoin",
    "coinType": 0,
    "namespace": "bip122",
    "reference": "000000000019d6689c085ae165831e93"
  }
];

export const byChainId: Record<string, ChainInfo> = {
  "1": {
    "chainId": 1,
    "shortName": "eth",
    "name": "Ethereum Mainnet",
    "coinType": 60,
    "namespace": "eip155",
    "reference": "1"
  },
  "10": {
    "chainId": 10,
    "shortName": "oeth",
    "name": "OP Mainnet",
    "coinType": 2147483658,
    "namespace": "eip155",
    "reference": "10"
  },
  "56": {
    "chainId": 56,
    "shortName": "bnb",
    "name": "BNB Smart Chain Mainnet",
    "coinType": 714,
    "namespace": "eip155",
    "reference": "56"
  },
  "137": {
    "chainId": 137,
    "shortName": "pol",
    "name": "Polygon Mainnet",
    "coinType": 966,
    "namespace": "eip155",
    "reference": "137"
  },
  "1101": {
    "chainId": 1101,
    "shortName": "zkevm",
    "name": "Polygon zkEVM",
    "coinType": 2147484749,
    "namespace": "eip155",
    "reference": "1101"
  },
  "8453": {
    "chainId": 8453,
    "shortName": "base",
    "name": "Base",
    "coinType": 2147492101,
    "namespace": "eip155",
    "reference": "8453"
  },
  "42161": {
    "chainId": 42161,
    "shortName": "arb1",
    "name": "Arbitrum One",
    "coinType": 2147525809,
    "namespace": "eip155",
    "reference": "42161"
  },
  "42220": {
    "chainId": 42220,
    "shortName": "celo",
    "name": "Celo Mainnet",
    "coinType": 2147525868,
    "namespace": "eip155",
    "reference": "42220"
  },
  "43114": {
    "chainId": 43114,
    "shortName": "avax",
    "name": "Avalanche C-Chain",
    "coinType": 9005,
    "namespace": "eip155",
    "reference": "43114"
  },
  "59144": {
    "chainId": 59144,
    "shortName": "linea",
    "name": "Linea",
    "coinType": 2147542792,
    "namespace": "eip155",
    "reference": "59144"
  },
  "534352": {
    "chainId": 534352,
    "shortName": "scr",
    "name": "Scroll",
    "coinType": 2148018000,
    "namespace": "eip155",
    "reference": "534352"
  },
  "7777777": {
    "chainId": 7777777,
    "shortName": "zora",
    "name": "Zora",
    "coinType": 2155261425,
    "namespace": "eip155",
    "reference": "7777777"
  },
  "solana": {
    "chainId": "solana",
    "shortName": "solana",
    "name": "Solana",
    "coinType": 501,
    "namespace": "solana",
    "reference": "So11111111111111111111111111111111111111112"
  },
  "bitcoin": {
    "chainId": "bitcoin",
    "shortName": "bitcoin",
    "name": "Bitcoin",
    "coinType": 0,
    "namespace": "bip122",
    "reference": "000000000019d6689c085ae165831e93"
  }
};

export const byShortName: Record<string, ChainInfo> = {
  "eth": {
    "chainId": 1,
    "shortName": "eth",
    "name": "Ethereum Mainnet",
    "coinType": 60,
    "namespace": "eip155",
    "reference": "1"
  },
  "pol": {
    "chainId": 137,
    "shortName": "pol",
    "name": "Polygon Mainnet",
    "coinType": 966,
    "namespace": "eip155",
    "reference": "137"
  },
  "bnb": {
    "chainId": 56,
    "shortName": "bnb",
    "name": "BNB Smart Chain Mainnet",
    "coinType": 714,
    "namespace": "eip155",
    "reference": "56"
  },
  "avax": {
    "chainId": 43114,
    "shortName": "avax",
    "name": "Avalanche C-Chain",
    "coinType": 9005,
    "namespace": "eip155",
    "reference": "43114"
  },
  "oeth": {
    "chainId": 10,
    "shortName": "oeth",
    "name": "OP Mainnet",
    "coinType": 2147483658,
    "namespace": "eip155",
    "reference": "10"
  },
  "base": {
    "chainId": 8453,
    "shortName": "base",
    "name": "Base",
    "coinType": 2147492101,
    "namespace": "eip155",
    "reference": "8453"
  },
  "arb1": {
    "chainId": 42161,
    "shortName": "arb1",
    "name": "Arbitrum One",
    "coinType": 2147525809,
    "namespace": "eip155",
    "reference": "42161"
  },
  "zkevm": {
    "chainId": 1101,
    "shortName": "zkevm",
    "name": "Polygon zkEVM",
    "coinType": 2147484749,
    "namespace": "eip155",
    "reference": "1101"
  },
  "linea": {
    "chainId": 59144,
    "shortName": "linea",
    "name": "Linea",
    "coinType": 2147542792,
    "namespace": "eip155",
    "reference": "59144"
  },
  "zora": {
    "chainId": 7777777,
    "shortName": "zora",
    "name": "Zora",
    "coinType": 2155261425,
    "namespace": "eip155",
    "reference": "7777777"
  },
  "scr": {
    "chainId": 534352,
    "shortName": "scr",
    "name": "Scroll",
    "coinType": 2148018000,
    "namespace": "eip155",
    "reference": "534352"
  },
  "celo": {
    "chainId": 42220,
    "shortName": "celo",
    "name": "Celo Mainnet",
    "coinType": 2147525868,
    "namespace": "eip155",
    "reference": "42220"
  },
  "solana": {
    "chainId": "solana",
    "shortName": "solana",
    "name": "Solana",
    "coinType": 501,
    "namespace": "solana",
    "reference": "So11111111111111111111111111111111111111112"
  },
  "bitcoin": {
    "chainId": "bitcoin",
    "shortName": "bitcoin",
    "name": "Bitcoin",
    "coinType": 0,
    "namespace": "bip122",
    "reference": "000000000019d6689c085ae165831e93"
  }
};

export const byNameSpaceReference: Record<string, ChainInfo> = {
  "So11111111111111111111111111111111111111112": {
    "chainId": "solana",
    "shortName": "solana",
    "name": "Solana",
    "coinType": 501,
    "namespace": "solana",
    "reference": "So11111111111111111111111111111111111111112"
  },
  "000000000019d6689c085ae165831e93": {
    "chainId": "bitcoin",
    "shortName": "bitcoin",
    "name": "Bitcoin",
    "coinType": 0,
    "namespace": "bip122",
    "reference": "000000000019d6689c085ae165831e93"
  }
};

export const MANUAL_CHAINS: Record<string, ChainInfo> = {
  "solana": {
    "chainId": "solana",
    "shortName": "solana",
    "name": "Solana",
    "coinType": 501,
    "namespace": "solana",
    "reference": "So11111111111111111111111111111111111111112"
  },
  "bitcoin": {
    "chainId": "bitcoin",
    "shortName": "bitcoin",
    "name": "Bitcoin",
    "coinType": 0,
    "namespace": "bip122",
    "reference": "000000000019d6689c085ae165831e93"
  }
};
